//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Domain.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eCommerce.Domain.Exceptions.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category already has product and can&apos;t be a parent category.
        /// </summary>
        internal static string CategoryHasProductExceptionMessage {
            get {
                return ResourceManager.GetString("CategoryHasProductExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title already exists in a neighboor category.
        /// </summary>
        internal static string CategoryNeighboorTitleExistsExceptionMessage {
            get {
                return ResourceManager.GetString("CategoryNeighboorTitleExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category does not exist.
        /// </summary>
        internal static string CategoryNotExistExceptionMessage {
            get {
                return ResourceManager.GetString("CategoryNotExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category can not be parent category for itself.
        /// </summary>
        internal static string CategoryOwnParentCategoryExcpetionMessage {
            get {
                return ResourceManager.GetString("CategoryOwnParentCategoryExcpetionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add product to categories with sub category.
        /// </summary>
        internal static string ProductCategoryWithSubCategoryExceptionMessage {
            get {
                return ResourceManager.GetString("ProductCategoryWithSubCategoryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product description can&apos;t be shorter than 10 letters.
        /// </summary>
        internal static string ProductDescriptionShorterThanTenLettersExceptionMessage {
            get {
                return ResourceManager.GetString("ProductDescriptionShorterThanTenLettersExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has to have at least one photo.
        /// </summary>
        internal static string ProductPhotoCountZeroExceptionMessage {
            get {
                return ResourceManager.GetString("ProductPhotoCountZeroExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product price can not be less than or equal to zero.
        /// </summary>
        internal static string ProductPriceNegativeOrZeroExceptionMessage {
            get {
                return ResourceManager.GetString("ProductPriceNegativeOrZeroExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product stock can&apos;t be a negative number.
        /// </summary>
        internal static string ProductStockNegativeExceptionMessage {
            get {
                return ResourceManager.GetString("ProductStockNegativeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product title has to be unique.
        /// </summary>
        internal static string ProductTitleExistExceptionMessage {
            get {
                return ResourceManager.GetString("ProductTitleExistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product title can&apos;t be shorter than 5 letters.
        /// </summary>
        internal static string ProductTitleShortenThanFiveLettersExceptionMessage {
            get {
                return ResourceManager.GetString("ProductTitleShortenThanFiveLettersExceptionMessage", resourceCulture);
            }
        }
    }
}
